name: Eufy Mega Security
version: "0.1.121-test16"
slug: eufy_event_gateway
description: Event-first Eufy camera bridge for Home Assistant
url: https://github.com/mscodemonkey/eufy-mega-security
startup: application
boot: auto
init: false
arch:
  - aarch64
  - amd64
ports:
  3218/tcp: null
ports_description:
  3218/tcp: Gateway API
watchdog: http://[HOST]:[PORT:3218]/live
ingress: true
ingress_port: 3218
panel_icon: mdi:cctv
host_network: true
hassio_api: true
discovery:
  - eufy_event_gateway
options:
  username: ""
  password: ""
  country: AU
  verification_code: ""
schema:
  username: str
  password: password
  country: str
  verification_code: str
